# Generated by Django 3.1.7 on 2021-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryitem',
            name='measurement_type',
            field=models.IntegerField(choices=[(1, 'Weight'), (2, 'Packaging')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'dry'), (2, 'wet')], default='', max_length=100),
        ),
    ]
