# Generated by Django 3.1.7 on 2021-02-21 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20210220_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryitem',
            name='measurement_type',
            field=models.IntegerField(choices=[(1, 'Weight'), (2, 'Packaging')], default=1),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='sku',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='type',
            field=models.IntegerField(choices=[(1, 'dry'), (2, 'wet')], default=1),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_bakery_item', models.PositiveSmallIntegerField()),
                ('order_price', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=8, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[(1, 'Success'), (2, 'Failed'), (3, 'Pending')], max_length=5, null=True)),
                ('return_delivery', models.CharField(blank=True, max_length=5, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('guidelines', models.TextField(default='')),
                ('cancel', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inventory_items', models.ManyToManyField(to='api.Inventory')),
            ],
        ),
    ]
