# Generated by Django 3.1.7 on 2021-02-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210221_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='manufacturing_date',
        ),
    ]
