# Generated by Django 3.1.7 on 2021-02-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210221_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='inventory_item',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='bakery_item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bakery_item_order', to='api.bakeryitem'),
            preserve_default=False,
        ),
    ]
